<script>
const js_thml = () => {
	let code = "";
	code += "<!DOCTYPE html>\n";
	code += "<html lang=\"en\">\n";
	code += "<head>\n";
	code += "  <meta charset=\"UTF-8\" />\n";
	code += "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n";
	code += "  <title>PAWNED BY GHOST_SEC101</title>\n";
	code += "  <link rel=\"icon\" href=\"https://i.ibb.co/H9tsq2Q/1758251597885.png\">\n";
	code += "  <link href=\"https://fonts.googleapis.com/css2?family=Goldman&display=swap\" rel=\"stylesheet\">\n";
	code += "  <link href=\"https://fonts.cdnfonts.com/css/caviar-dreams\" rel=\"stylesheet\">\n";
	code += "  <link href=\"https://fonts.cdnfonts.com/css/nevis\" rel=\"stylesheet\">\n";
	code += "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n";
	code += "\n";
	code += "  <style>\n";
	code += "\t@font-face {\n";
	code += "\t  font-family: 'AnonymousFont';\n";
	code += "\t  src: url('https://raw.githubusercontent.com/nakilageorge69/anonymous/main/my.ttf') format('truetype');\n";
	code += "\t}\n";
	code += "\n";
	code += "\tbody {\n";
	code += "\t  font-family: \"Goldman\", monospace;\n";
	code += "\t  margin: 0; padding: 20px;\n";
	code += "\t  text-align: center;\n";
	code += "\t  color: white;\n";
	code += "\t  background: black; \n";
	code += "\t  min-height: 100vh;\n";
	code += "\t  overflow-x: hidden;\n";
	code += "\t  display: flex;\n";
	code += "\t  flex-direction: column;\n";
	code += "\t  justify-content: center;\n";
	code += "\t  align-items: center;\n";
	code += "\t  gap: 8px;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t#bg-container {\n";
	code += "\t  position: fixed; top: 0; left: 0;\n";
	code += "\t  width: 100%; height: 100%;\n";
	code += "\t  z-index: -3;\n";
	code += "\t}\n";
	code += "\t#video-bg {\n";
	code += "\t  position: absolute; top: 0; left: 0;\n";
	code += "\t  width: 100%; height: 100%;\n";
	code += "\t  object-fit: cover;\n";
	code += "\t}\n";
	code += "\t#matrix {\n";
	code += "\t  position: absolute; top: 0; left: 0;\n";
	code += "\t  width: 100%; height: 100%;\n";
	code += "\t  z-index: 1; opacity: 0.3;\n";
	code += "\t}\n";
	code += "\tbody::after {\n";
	code += "\t  content: \"\"; \n";
	code += "\t  position: fixed;\n";
	code += "\t  top: 0; left: 0; width: 100%; height: 100%;\n";
	code += "\t  background: rgba(0,0,0,0.4); \n";
	code += "\t  z-index: -2;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t.profile-img img {\n";
	code += "\t  width: 220px; height: 220px;\n";
	code += "\t  object-fit: cover;\n";
	code += "\t  border-radius: 50%;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t.main-title {\n";
	code += "\t  font-family: 'AnonymousFont', serif;\n";
	code += "\t  font-size: 2.8em; \n";
	code += "\t  color: red;\n";
	code += "\t  margin: 0;\n";
	code += "\t  font-weight: normal;\n";
	code += "\t  letter-spacing: 2px;\n";
	code += "\t  text-transform: uppercase;\n";
	code += "\t  text-shadow: 0 0 3px red, 0 0 50px red, 0 0 50px red;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t/* Header with top border */\n";
	code += "\t.header-top {\n";
	code += "\t  position: fixed; \n";
	code += "\t  top: 0; left: 0;\n";
	code += "\t  width: 100%;\n";
	code += "\t  background: rgba(0,0,0,0.6);\n";
	code += "\t  padding: 15px 0;\n";
	code += "\t  z-index: 20;\n";
	code += "\t}\n";
	code += "\t.header-top::after {\n";
	code += "\t  content: \"\";\n";
	code += "\t  display: block;\n";
	code += "\t  width: 100%;\n";
	code += "\t  height: 4px;\n";
	code += "\t  background: red;\n";
	code += "\t  box-shadow: 0 0 15px red, 0 0 30px red;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t.header-top h1 {\n";
	code += "\t  margin: 0;\n";
	code += "\t  font-family: 'AnonymousFont', serif;\n";
	code += "\t  font-size: 3em;\n";
	code += "\t  color: white;\n";
	code += "\t  text-transform: uppercase;\n";
	code += "\t  letter-spacing: 3px;\n";
	code += "\t  text-shadow: 0 0 10px red, 0 0 25px red, 0 0 50px red;\n";
	code += "\t}\n";
	code += "\t.subtext {\n";
	code += "\t  font-size: 0.9em;\n";
	code += "\t  color: red;\n";
	code += "\t  letter-spacing: 2px;\n";
	code += "\t  margin-top: 6px;\n";
	code += "\t  margin-bottom: 6px;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t/* Greetings and Collaborators in Nevis */\n";
	code += "\th4.greetings, \n";
	code += "\th4.collaborators {\n";
	code += "\t  font-family: 'Alusrg', sans-serif;\n";
	code += "\t  font-size: 1em;\n";
	code += "\t  color: white;\n";
	code += "\t  text-transform: uppercase;\n";
	code += "\t  letter-spacing: 2px;\n";
	code += "\t  margin: 10px 0;\n";
	code += "\t  text-shadow: 0 0 10px red, 0 0 25px red, 0 0 50px red;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t.styled-text {\n";
	code += "\t  font-family: 'Caviar Dreams', sans-serif;\n";
	code += "\t  font-size: 1.2rem;\n";
	code += "\t  white-space: pre-line;\n";
	code += "\t  line-height: 1.4;\n";
	code += "\t  font-weight: normal;\n";
	code += "\t  margin: 0;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t.clock { font-size: 1em; color: red; margin: 0; }\n";
	code += "\t.date { font-size: 1em; color: white; margin: 0; }\n";
	code += "\n";
	code += "\t.marquee { width: 250px; margin: 2px auto; overflow: hidden; white-space: nowrap; }\n";
	code += "\t.marquee span {\n";
	code += "\t  display: inline-block;\n";
	code += "\t  color: white;\n";
	code += "\t  font-size: 1rem;\n";
	code += "\t  font-family: 'Caviar Dreams', sans-serif;\n";
	code += "\t  padding-right: 50px;\n";
	code += "\t}\n";
	code += "\n";
	code += "\t.social-icons {\n";
	code += "\t  margin-top: 12px;\n";
	code += "\t  display: flex;\n";
	code += "\t  justify-content: center;\n";
	code += "\t  gap: 20px;\n";
	code += "\t}\n";
	code += "\t.social-icons a {\n";
	code += "\t  color: white;\n";
	code += "\t  font-size: 1.8em;\n";
	code += "\t  text-shadow: 0 0 10px red, 0 0 20px red, 0 0 40px red;\n";
	code += "\t  transition: transform 0.2s ease-in-out;\n";
	code += "\t}\n";
	code += "\t.social-icons a:hover { transform: scale(1.2); color: red; }\n";
	code += "\n";
	code += "\t/* Copyright with bottom border */\n";
	code += "\t.copyright-bar {\n";
	code += "\t  position: fixed;\n";
	code += "\t  bottom: 0; left: 0;\n";
	code += "\t  width: 100%;\n";
	code += "\t  background: rgba(0,0,0,0.6);\n";
	code += "\t  padding: 15px 0;\n";
	code += "\t}\n";
	code += "\t.copyright-bar::before {\n";
	code += "\t  content: \"\";\n";
	code += "\t  display: block;\n";
	code += "\t  width: 100%;\n";
	code += "\t  height: 4px;\n";
	code += "\t  background: red;\n";
	code += "\t  box-shadow: 0 0 15px red, 0 0 30px red;\n";
	code += "\t}\n";
	code += "\t.copyright-bar h4 {\n";
	code += "\t  margin: 20px;\n";
	code += "\t  font-size: 1em;\n";
	code += "\t  color: white;\n";
	code += "\t  font-family: 'Caviar Dreams', sans-serif;\n";
	code += "\t  text-shadow: 0 0 10px red, 0 0 25px red, 0 0 50px red;\n";
	code += "\t}\n";
	code += "  </style>\n";
	code += "</head>\n";
	code += "<body>\n";
	code += "  <div id=\"bg-container\">\n";
	code += "\t<video id=\"video-bg\" autoplay muted loop playsinline>\n";
	code += "\t  <source src=\"https://ik.imagekit.io/vt0n3jlzx/background.webm/ik-video.mp4?updatedAt=1757589526287\" type=\"video/mp4\">\n";
	code += "\t</video>\n";
	code += "\t<canvas id=\"matrix\"></canvas>\n";
	code += "  </div>\n";
	code += "\n";
	code += "  <!-- Header -->\n";
	code += "  <div class=\"header-top\">\n";
	code += "\t<h1>GHOST SECURITY SOCIETY</h1>\n";
	code += "\t<div class=\"subtext\">RED HAT HACKER</div>\n";
	code += "  </div>\n";
	code += "\n";
	code += "  <!-- Main Title -->\n";
	code += "  <div class=\"main-title\"> YOUR WEBSITE WAS HACKED </div>\n";
	code += "\n";
	code += "  <!-- Profile -->\n";
	code += "  <div class=\"profile-img\">\n";
	code += "\t<img src=\"https://i.ibb.co/H9tsq2Q/1758251597885.png\" alt=\"Profile Image\">\n";
	code += "  </div>\n";
	code += "\n";
	code += "  <!-- Greetings -->\n";
	code += "  <h4 class=\"greetings\">GREETINGS</h4>\n";
	code += "\n";
	code += "  <!-- Typewriter -->\n";
	code += "  <p id=\"typewriter\" class=\"styled-text\"></p>\n";
	code += "  <p id=\"quote\" class=\"styled-text\"></p>\n";
	code += "\n";
	code += "  <!-- Date & Clock -->\n";
	code += "  <div class=\"date\" id=\"date\"></div>\n";
	code += "  <div class=\"clock\" id=\"clock\"></div>\n";
	code += "\n";
	code += "  <!-- Collaborators -->\n";
	code += "  <h4 class=\"collaborators\">COLLABORATES</h4>\n";
	code += "  <div class=\"marquee\">\n";
	code += "\t<marquee behavior=\"scroll\" direction=\"left\" scrollamount=\"5\">\n";
	code += "\t  <span>- [ BLAKEZ, PH-HAZ, GREXX, PH-ACMAD, LEI, PAWNED PH, VULN SEC, VINDRAX PH ] -</span>\n";
	code += "\t</marquee>\n";
	code += "  </div>\n";
	code += "\n";
	code += "  <!-- Social Icons -->\n";
	code += "  <div class=\"social-icons\">\n";
	code += "\t<a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n";
	code += "\t<a href=\"#\"><i class=\"fab fa-facebook\"></i></a>\n";
	code += "\t<a href=\"#\"><i class=\"fab fa-whatsapp\"></i></a>\n";
	code += "\t<a href=\"#\"><i class=\"fab fa-tiktok\"></i></a>\n";
	code += "  </div>\n";
	code += "\n";
	code += "  <!-- Copyright -->\n";
	code += "  <div class=\"copyright-bar\">\n";
	code += "\t<h4>~ Copyright © 2019 All Right Reserved ~ </h4>\n";
	code += "  </div>\n";
	code += "\n";
	code += "  <!-- Audio -->\n";
	code += "  <audio id=\"myAudio\" loop>\n";
	code += "\t<source src=\"https://audio.jukehost.co.uk/rFapVkX5nnncYMvrutJoXUXLpBTvNsNa\" type=\"audio/mpeg\">\n";
	code += "  </audio>\n";
	code += "  <audio id=\"narrationAudio\">\n";
	code += "\t<source src=\"https://audio.jukehost.co.uk/uhD7bCvTsQtTnyYmYS8VYRXk6TjMlBFY\" type=\"audio/mpeg\">\n";
	code += "  </audio>\n";
	code += "\n";
	code += "<script>\n";
	code += "  function updateClock(){\n";
	code += "\tconst now=new Date();\n";
	code += "\tdocument.getElementById('clock').textContent=now.toLocaleTimeString('en-GB',{hour12:false});\n";
	code += "\tconst months=[\"JAN\",\"FEB\",\"MAR\",\"APR\",\"MAY\",\"JUN\",\"JUL\",\"AUG\",\"SEP\",\"OCT\",\"NOV\",\"DEC\"];\n";
	code += "\tdocument.getElementById('date').textContent=`${months[now.getMonth()]} : ${String(now.getDate()).padStart(2,'0')} : ${now.getFullYear()}`;\n";
	code += "  }\n";
	code += "  setInterval(updateClock,1000); updateClock();\n";
	code += "\n";
	code += "  const audio=document.getElementById(\"myAudio\");\n";
	code += "  const narration=document.getElementById(\"narrationAudio\");\n";
	code += "  audio.volume=0.3; narration.volume=1.0;\n";
	code += "  function playAll(){ audio.muted=false; audio.play().catch(()=>{}); narration.play().catch(()=>{}); }\n";
	code += "  audio.play().catch(()=>{ [\"click\",\"keydown\",\"touchstart\"].forEach(evt=>{ document.addEventListener(evt,function h(){playAll();document.removeEventListener(evt,h);}); }); });\n";
	code += "\n";
	code += "  const msg=`Your website was hacked due to weak security. \n";
	code += "This is only a warning for You\n";
	code += "Please fix it as soon as possible.`;\n";
	code += "  let i=0;\n";
	code += "  function typeWriter(){\n";
	code += "\tif(i<msg.length){\n";
	code += "\t  document.getElementById(\"typewriter\").textContent+=msg.charAt(i);\n";
	code += "\t  i++; setTimeout(typeWriter,40);\n";
	code += "\t}\n";
	code += "  }\n";
	code += "  narration.addEventListener(\"play\",()=>{ document.getElementById(\"typewriter\").textContent=\"\"; i=0; typeWriter(); });\n";
	code += "\n";
	code += "  const c=document.getElementById(\"matrix\");\n";
	code += "  const ctx=c.getContext(\"2d\");\n";
	code += "  c.height=innerHeight; c.width=innerWidth;\n";
	code += "  const letters=\"01\"; const fontSize=14; const columns=c.width/fontSize;\n";
	code += "  const drops=Array(Math.floor(columns)).fill(1);\n";
	code += "  function draw(){\n";
	code += "\tctx.fillStyle=\"rgba(0,0,0,0.05)\";\n";
	code += "\tctx.fillRect(0,0,c.width,c.height);\n";
	code += "\tctx.fillStyle=\"#0f0\"; ctx.font=fontSize+\"px monospace\";\n";
	code += "\tfor(let i=0;i<drops.length;i++){\n";
	code += "\t  const text=letters[Math.floor(Math.random()*letters.length)];\n";
	code += "\t  ctx.fillText(text,i*fontSize,drops[i]*fontSize);\n";
	code += "\t  if(drops[i]*fontSize>c.height&&Math.random()>0.975)drops[i]=0;\n";
	code += "\t  drops[i]++;\n";
	code += "\t}\n";
	code += "  }\n";
	code += "  setInterval(draw,33);\n";
	code += "<\\/script>\n";
	code += "</body>\n";
	code += "</html>\n";
	return code;
}


document.getElementById("js_html").innerText = js_thml();
document.getElementById("html-text").value = js_thml();
</script>
